version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api/slots-seed.json:/app/slots-seed.json

  client:
    build:
      context: ./client
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - PORT=3001
    depends_on:
      - api
